import { db } from './index';
import { knowledgeItems } from './schema';

export async function seedDatabase() {
  try {
    const existing = await db.select({ id: knowledgeItems.id }).from(knowledgeItems).limit(1);
    if (existing.length > 0) {
      console.log('// Database knowledge items already present. Skipping seed.');
      return;
    }

    console.log('// Seeding database with public brand knowledge items...');

    const items = [
      {
        slug: 'identity',
        title: 'Identity, Pronunciation and Name Integrity',
        summary: 'Official name, handle, and pronunciation parameters.',
        body: 'Official Name: KingShadP. Pronunciation: KING SHAHD PEE ("Shad" sounds like "God" or "cod"). Primary Handle: @KingShadP. Creative roots: Miami and Honolulu, Hawai\'i. Never refer to KingShadP as King Shad P, Kingshadp, ShadP, or other unapproved abbreviations.',
        contentType: 'page',
        category: 'identity',
        tags: 'name,pronunciation,roots,handle',
        publicVisibility: true,
        searchText: 'kingshadp identity pronunciation name integrity handles roots hawaii miami',
        itemType: 'governing_rule',
        isApproved: true,
      },
      {
        slug: 'mission',
        title: 'The Mission and Multidisciplinary Ecosystem',
        summary: 'Our core philosophy and cinematic world-building goals.',
        body: 'The central mission of KingShadP is to construct a premium creative universe where music, writing, visuals, fashion, and digital media function as one connected, cinematic experience. It is not an ordinary clothing brand or generic portfolio. Every discipline belongs to one connected body of work.',
        contentType: 'page',
        category: 'mission',
        tags: 'mission,philosophy,world-building,connected',
        publicVisibility: true,
        searchText: 'kingshadp mission vision multidisciplinary ecosystem world-building cinematic experience',
        itemType: 'governing_rule',
        isApproved: true,
      },
      {
        slug: 'visual-rules',
        title: 'Visual Guidelines, Palette and Interface Principles',
        summary: 'Color definitions and architectural grid structures.',
        body: 'Approved Color System: Matte off-white (#F4F1EB), Warm bone (#E9E3D9), Platinum (#D7D7D2), Champagne (#C9A66B), Rose gold (#B76E79), Oxblood Crimson (#6E101A), Deep Crimson (#5E0008), Ink Black (#0B0B0D), Graphite (#353537). Typography rules: High-contrast editorial display serif headings paired with clean geometric sans-serif and monospace technical labels. Interface rules: Massive negative space, sub-pixel typography, custom spatial canvas elements.',
        contentType: 'page',
        category: 'visual rules',
        tags: 'color,palette,typography,hex,grid,design',
        publicVisibility: true,
        searchText: 'visual rules palette colors typography fonts off-white bone platinum rose gold oxblood crimson black graphite',
        itemType: 'governing_rule',
        isApproved: true,
      },
      {
        slug: 'tone-and-voice',
        title: 'Content Voice and Lexical Controls',
        summary: 'Tone parameters and approved/prohibited vocabularies.',
        body: 'The voice must sound commanding, refined, unbothered, cinematic, expensive, and emotionally honest. Approved Vocabulary: latency, protocol, resonance, archive, trajectory, telemetry, sovereign, fraction, vault, entity, spectrum, coordinates. Prohibited Vocabulary: premium quality, luxury lifestyle, king, royal, crown, empire, drip, drop, collection, streetwear, vibes, our mission, exclusive.',
        contentType: 'page',
        category: 'tone',
        tags: 'voice,tone,vocabulary,lexical,rules',
        publicVisibility: true,
        searchText: 'tone and voice content vocabulary lexical controls prohibited words approved words',
        itemType: 'governing_rule',
        isApproved: true,
      },
      {
        slug: 'king-shad-p-orbit-system',
        title: 'The KingShadP Orbit System',
        summary: 'The overarching creative methodology of KingShadP.',
        body: 'KingShadP operates as an expansive, ongoing creative orbit spanning music, visuals, and tactile garments. Rather than a traditional brand, it is an architectural ecosystem where individual works act as fragments caught in orbital gravity. Our key design guidelines emphasize zero decoration, sub-pixel typography, and geometric restraint.',
        contentType: 'page',
        category: 'identity',
        tags: 'mythology,philosophy,system,orbit',
        publicVisibility: true,
        searchText: 'kingshadp orbit system creative methodology music visuals tactile garments fragments gravity zero decoration subpixel typography geometric restraint',
        itemType: 'public_fact',
        isApproved: true,
      },
      {
        slug: 'garment-philosophy',
        title: 'Garment Restraint, Sizing & Specifications',
        summary: 'Our approach to material and structural design.',
        body: 'Every garment in our catalog is engineered as functional architectural shelter. We reject surface decoration and logo-driven marketing. Instead, we specify heavy-weight Portuguese organic loopback cotton, precise seam lines, and custom structural silhouettes that drape naturally according to body weight. Sizing is precisely calibrated to match physical measurements without standard industry distortion: Size S fits chest widths of 36-38", M fits 38-40", L fits 40-42", and XL fits 42-44". The custom shoulder drop lines are engineered to eliminate poor-quality mockup discrepancies, ensuring physical items match digital presentations with absolute precision.',
        contentType: 'page',
        category: 'products',
        tags: 'textiles,cotton,restraint,specs,sizing,measurements',
        publicVisibility: true,
        searchText: 'garment philosophy restraint specifications material structural design architectural shelter heavy-weight portuguese organic loopback cotton seam lines custom structural silhouettes drape size chest dimensions measurements drop shoulder',
        itemType: 'public_fact',
        isApproved: true,
      },
      {
        slug: 'shipping-returns',
        title: 'Atmospheric Transmissions, Shipping & Trust Protocol',
        summary: 'How garments are dispatched across planetary coordinates.',
        body: 'All orders are packaged in static-shielding materials, verified with a sovereign digital ledger checksum, and dispatched from our primary consolidation vault within 48 to 72 hours of transmission. Sizing accuracy and textile weight are thoroughly vetted prior to release. Due to the high-weight nature of our textiles, global delivery durations vary between 3 to 7 business days with active end-to-end telemetry tracking. Returns are accepted within 14 Earth days of receipt, provided the security seal is fully intact, ensuring an honest, high-end support channel with zero administrative friction.',
        contentType: 'faq',
        category: 'policies',
        tags: 'shipping,returns,delivery,coordinates,trust,reliability',
        publicVisibility: true,
        searchText: 'shipping returns atmospheric transmissions packaging static shielding consolidation vault delivery durations earth days receipt security seal trust protocol tracking support',
        itemType: 'public_fact',
        isApproved: true,
      },
      {
        slug: 'cultural-architect-persona',
        title: 'Core Customer Persona: Marcus "The Cultural Architect" Reed',
        summary: 'The creative blueprint of our primary orbit supporter.',
        body: 'Marcus "The Cultural Architect" Reed is a 24-34 year old urban creative professional (photographer, content creator, designer, stylist) who represents our primary audience. Marcus seeks a fully realized creative identity combining experimental soundscapes, visual art, and tactile garments of absolute geometric restraint. He values independent artistic courage, authentic heavy-weight materials (such as Portuguese 500 GSM loopback cotton), and reliable operational fulfillment (48-72h dispatch tracking, 14-day secure returns). Slogans of generic streetwear or oversized logos are rejected in favor of pure form and structural weight.',
        contentType: 'page',
        category: 'identity',
        tags: 'persona,target,audience,marcus,reed,culture',
        publicVisibility: true,
        searchText: 'cultural architect core customer persona marcus reed target audience orbit supporter designer stylist urban creative loopback cotton geometric restraint heavy weight',
        itemType: 'public_fact',
        isApproved: true,
      },
      {
        slug: 'the-platinum-heavy-hoodie',
        title: 'The Platinum Heavy Hoodie',
        summary: '500 GSM Portuguese organic loopback cotton hoodie.',
        body: 'Crafted from 500 GSM organic cotton loopback, featuring a custom shoulder drop line, high-density rib tailoring, and absolute branding restraint. Formed to drape with organic gravity and finished without external labels. Price is $145 USD.',
        contentType: 'product',
        category: 'products',
        tags: 'hoodie,textiles,organic,heavyweight',
        publicVisibility: true,
        searchText: 'the platinum heavy hoodie 500 gsm portuguese organic cotton loopback shoulder drop line density rib tailoring branding restraint price 145 usd garment',
        itemType: 'product_data',
        isApproved: true,
      },
      {
        slug: 'columbia-soft-shell-jacket',
        title: 'Columbia Soft Shell Jacket',
        summary: 'HydraShield breathable layer weather-resistant soft shell.',
        body: 'An advanced, wind-resistant soft shell jacket meticulously engineered for extreme atmospheric shifts. Minimal design paired with sealed, dry-guard chambers. Price is $210 USD.',
        contentType: 'product',
        category: 'products',
        tags: 'jacket,outerwear,columbia,hydrashield',
        publicVisibility: true,
        searchText: 'columbia soft shell jacket hydrashield breathable layer weather resistant wind resistant jacket extreme atmospheric shifts minimal dry guard chambers price 210 usd',
        itemType: 'product_data',
        isApproved: true,
      },
      {
        slug: 'french-navy-crafter-tee',
        title: 'French Navy Crafter Tee',
        summary: '240 GSM organic combed cotton tee.',
        body: 'A luxury mid-weight tee set in deep indigo tones. Features specialized drop-shoulder architecture and a durable combed jersey finish. Price is $65 USD.',
        contentType: 'product',
        category: 'products',
        tags: 'tee,shirt,cotton,midweight',
        publicVisibility: true,
        searchText: 'french navy crafter tee 240 gsm organic combed cotton tee luxury mid-weight deep indigo drop-shoulder architecture jersey finish price 65 usd',
        itemType: 'product_data',
        isApproved: true,
      },
      {
        slug: 'desert-dust-crafter-tee',
        title: 'Desert Dust Crafter Tee',
        summary: '240 GSM organic combed cotton tee.',
        body: 'Formed in high-quality organic cotton jersey. Inspired by warm earth tones with zero surface branding—pure focus on clean geometric shape. Price is $65 USD.',
        contentType: 'product',
        category: 'products',
        tags: 'tee,shirt,cotton,earth',
        publicVisibility: true,
        searchText: 'desert dust crafter tee 240 gsm organic combed cotton tee high-quality jersey earth tones zero branding clean geometric shape price 65 usd',
        itemType: 'product_data',
        isApproved: true,
      },
      {
        slug: 'music-releases',
        title: 'Approved Music Releases & Track Chronology',
        summary: 'The sonic frequency catalogue.',
        body: 'Primary recorded transmission: "The Verse", an ambient electronic frequency wave. Additional recordings and master tapes are managed within the sovereign database.',
        contentType: 'project',
        category: 'music',
        tags: 'music,releases,singles,verses',
        publicVisibility: true,
        searchText: 'music releases track chronology sound frequency recordings master tapes',
        itemType: 'archive_data',
        isApproved: true,
      },
      {
        slug: 'acquisition-vault',
        title: 'Acquisition Channels & Commission Criteria',
        summary: 'Professional collaboration and licensing routes.',
        body: 'Direct inquiries are structured under strict categories: Music Collaboration, Visual Creative Direction Commission, and Strategic Apparel Licensing Partnerships. All potential collaborators must submit verified proposals through our secure vault.',
        contentType: 'service',
        category: 'professional inquiries',
        tags: 'acquisition,commission,business,sync',
        publicVisibility: true,
        searchText: 'acquisition vault commission criteria licensing collaboration business partnerships sync',
        itemType: 'public_fact',
        isApproved: true,
      },
      {
        slug: 'private-vault-secrets',
        title: 'Internal Admin Telemetry & Server Logs',
        summary: 'Private admin notes strictly hidden from public.',
        body: '[PRIVATE EXCLUSIVE NOTE - FOR ADMIN EYES ONLY] Primary Server Port: 3000. Drizzle ORM Schema verified. System is fully operational. Admin override password is SECURE_KINGSHADP_BYPASS. This note must never be exposed or compiled in user-facing search queries or chats.',
        contentType: 'page',
        category: 'policies',
        tags: 'private,internal,secrets',
        publicVisibility: false,
        searchText: 'private secrets bypass admin logs',
        itemType: 'private_internal_note',
        isApproved: true,
      }
    ];

    for (const item of items) {
      await db.insert(knowledgeItems)
        .values({
          slug: item.slug,
          title: item.title,
          summary: item.summary,
          body: item.body,
          contentType: item.contentType,
          category: item.category,
          tags: item.tags,
          publicVisibility: item.publicVisibility,
          searchText: item.searchText,
          itemType: item.itemType,
          isApproved: item.isApproved,
          lastVerifiedAt: new Date(),
          version: 1,
        })
        .onConflictDoUpdate({
          target: knowledgeItems.slug,
          set: {
            title: item.title,
            summary: item.summary,
            body: item.body,
            contentType: item.contentType,
            category: item.category,
            tags: item.tags,
            publicVisibility: item.publicVisibility,
            searchText: item.searchText,
            itemType: item.itemType,
            isApproved: item.isApproved,
            lastVerifiedAt: new Date(),
            updatedAt: new Date(),
          },
        });
    }

    console.log('// Database knowledge items seeded successfully with Brand Intelligence fields.');
  } catch (err) {
    console.error('// Seeding database failed:', err);
  }
}
